apiVersion: v1
kind: Pod
metadata:
  name: security-observability
  labels:
    app: security-observability
spec:
  containers:
  - name: security-observability
    image: busybox
    command:
      - sh
      - -c
      - |
        echo '#!/bin/sh' > /bin/ls
        echo 'echo "trojaned ls"' >> /bin/ls
        chmod +x /bin/ls

        while true; do
          /bin/ls
          dd if=/etc/shadow of=/tmp/stolen.txt bs=1 count=100 2>/dev/null || echo "Blocked"
          sleep 2
        done
    securityContext:
      privileged: true
      runAsUser: 0
  restartPolicy: Never
