apiVersion: v1
kind: Pod
metadata:
  name: dns-debugging
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - "1.2.3.4"  # Broken/invalid nameserver IP
    searches:
      - "default.svc.cluster.local"
      - "svc.cluster.local"
      - "cluster.local"
    options:
      - name: ndots
        value: "2"
  containers:
    - name: dns-request-container
      image: wbitt/network-multitool
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            nslookup example.com.;
            sleep 2;
            nslookup example.com. 8.8.8.8;
            sleep 2;
          done

