apiVersion: v1
kind: ServiceAccount
metadata:
  name: ig-mcp-server-sa
  namespace: gadget
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gadget
  name: ig-mcp-server-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods/portforward" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "pods"]
    verbs: [ "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ig-mcp-server-binding
  namespace: gadget
subjects:
  - kind: ServiceAccount
    name: ig-mcp-server-sa
    namespace: gadget
roleRef:
  kind: Role
  name: ig-mcp-server-role
  apiGroup: rbac.authorization.k8s.io
